[project]
name = "bsky-starter-pack-block"
version = "0.1.0"
description = "Block all users from a Bluesky starter pack or list"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = ["atproto>=0.0.65"]

[dependency-groups]
dev = ["pyrefly", "ruff>=0.2.2", "vermin>=1.7.0"]

[tool.ruff]
line-length = 79
target-version = "py312"
src = ["bsky.py"]

[tool.ruff.lint]
select = [
    "E",
    "EM",
    "W",
    "F",
    "I",
    "N",
    "UP",
    "B",
    "A",
    "C4",
    "PIE",
    "SIM",
    "RET",
    "ARG",
    "EM",
    "PTH",
    "PL",
    "RUF",
    "S",
    "BLE",
    "ANN",
    "ASYNC",
    "PT",
    "D101",
    "D102",
    "D103",
]
ignore = [
    "E501",
    "ISC001",
    "COM812",
    "D203",
    "D213",
    "ANN401",  # use Any in **kwargs
    "PLR0913",
    "PLR2004",
    "S101",
    "S311",
]

[tool.pyrefly]
project-includes = ["bsky.py"]
project-excludes = [".venv"]
python-version = "3.12"
site-package-path = ["stubs"]
preset = "strict"

[tool.pyrefly.errors]
assert-type = true
bad-override = true
bad-specialization = true
bad-context-manager = true
implicitly-defined-attribute = true
inconsistent-overload = true
invalid-overload = true
missing-attribute = true
no-access = true
redundant-cast = true
unbound-name = true
implicit-any-attribute = true
untyped-import = true
